title : "DiCheck (MeDical Check)"
description : "Membantu pengguna dalam mengakses informasi terkait dengan gejala penyakit yang sedang dialaminya"
exclude: ['README.md']

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme