version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb-container-dicheck
    ports:
      - "27015:27015"
    environment:
      - MONGO_INITDB_DATABASE=dicheck
    volumes:
      - mongodb-data:/data/db
    networks:
      - dicheck-network

  backend:
    build: ./backend
    container_name: backend-container-dicheck
    ports:
      - "8080:8080"
    networks:
      - dicheck-network
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb+srv://admin:jxSBhRHh8K39qRDT@dicheck.zesrlnd.mongodb.net/dicheck?retryWrites=true&w=majority&appName=dicheck
    volumes:
      - backend-logs:/app/logs

  frontend:
    build: ./frontend
    container_name: frontend-container-dicheck
    ports:
      - "3000:3000"
    networks:
      - dicheck-network
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend-container:8080

  ai:
    build: ./dataset_fix_dicheck
    container_name: ai-container-dicheck
    ports:
      - "8000:8000"
    networks:
      - dicheck-network
    depends_on:
      - backend
    environment:
      - PYTHONUNBUFFERED=1
      - BACKEND_URL=http://backend-container:8080

networks:
  dicheck-network:
    driver: bridge

volumes:
  mongodb-data:
  backend-logs:
