title : "DiCheck (MeDical Check)"
description : "Membantu pengguna dalam mengakses informasi terkait dengan gejala penyakit yang sedang dialaminya"
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme